apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-service-blue
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://github.com/folaoso23/quarkus-service-blue.git
    targetRevision: HEAD
